config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :goats, only: %i[index show create] do
    resources :bookings, only: %i[create new show]
    member do
      patch :favorite, :unfavorite
    end
  end
  get "users/:id/profile", to: "pages#profile", as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :goat
  belongs_to :user
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/goat.rb
class Goat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_favoritable
  has_one_attached :photo
  validates :rating, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 5.0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :goats
  has_many :bookings
  acts_as_favoritor

  # has_one_attached :profile_pic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  @goats = Goat.all
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @goat = Goat.find(params[:goat_id])
    dates = params[:dates].split(" to ")
    @start_date = Date.parse(dates[0])
    @end_date = Date.parse(dates[1])
    @days = (@end_date - @start_date).to_i
    @booking = Booking.new
  end

  def create
    @goat = Goat.find(params[:goat_id])
    @booking = Booking.new(user: current_user, goat: @goat, start_date: params[:start_date], end_date: params[:end_date])
    if @booking.save
      redirect_to user_profile_path(current_user.id)
    else
      render :new, status: :unprocessable_entity
      puts "that didn't work"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:dates)
  end
end

app/controllers/goats_controller.rb
class GoatsController < ApplicationController
  def index
    if params[:category]
      @goats = Goat.where(category: params[:category])
    else
      @goats = Goat.all
    end
    @markers = @goats.geocoded.map do |goat|
      { lat: goat.latitude, lng: goat.longitude, image_url: helpers.asset_url("goat.png") }
    end
  end

  def show
    @goat = Goat.find(params[:id])
    # raise
    @markers = [{ lat: @goat.latitude, lng: @goat.longitude, image_url: helpers.asset_url("goat.png") }]
  end

  def create
    @user = current_user
    @goat = Goat.new(goat_params)
    @goat.user = @user
    # raise
    if @goat.save
      redirect_to goat_path(@goat)
    else
      redirect_to user_profile_path(@user.id), status: :unprocessable_entity
    end
  end

  def unfavorite
    goat = Goat.find(params[:id])
    current_user.unfavorite(goat)

    redirect_to goats_path(goat)
  end

  def favorite
    goat = Goat.find(params[:id])
    current_user.favorite(goat)

    redirect_to goats_path(goat)
  end

  private

  def goat_params
    params.require(:goat).permit(:name, :category, :description, :price_per_day, :transport_fee, :cleaning_fee, :rating, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @user = current_user
    @my_goats = current_user.goats
    @goat = Goat.new
    @goats = Favorite.where(favoritor: @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def goat_categories
    Goat.distinct(:category).pluck(:category)
  end
end

app/views/bookings/new.html.erb
    <div class="py-5 text-center">
    <%= image_tag "goat.png" %>
      <h2>Ready to get GOATED?</h2>
      <p class="lead">We strive to bring you the finest goats. Our goats leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0"><%= @goat.name %></h6>
              <small class="text-muted">€<%= @goat.price_per_day %> X <%= @days %> days</small>
            </div>
            <span class="text-muted">€<%= @goat.price_per_day * @days %></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Transport Fee</h6>
            </div>
            <span class="text-muted">€<%= @goat.transport_fee %></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Cleaning Fee</h6>
            </div>
            <span class="text-muted">€<%= @goat.cleaning_fee %></span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (EUR)</span>
            <strong>€<%= (@goat.price_per_day * @days) + @goat.cleaning_fee + @goat.transport_fee %></strong>
          </li>
        </ul>

        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8 rounded border py-4">
        <h4 class="mb-3">Billing address</h4>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" placeholder="" value="<%= current_user.first_name %>" required="">
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" placeholder="" value="<%= current_user.last_name %>" required="">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com" value="<%= current_user.email %>">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required="">
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required="">
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required="">
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="row my-3">
          <div class="col-12 fs-3">
            <i class="fa-brands fa-cc-visa"></i>
            <i class="fa-brands fa-cc-mastercard"></i>
            <i class="fa-brands fa-cc-jcb"></i>
            <i class="fa-brands fa-cc-discover"></i>
            <i class="fa-brands fa-cc-amex"></i>
          </div>
          </div>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cc-name" class="form-label">Name on card</label>
              <input type="text" class="form-control" id="cc-name" placeholder="" required="">
              <small class="text-muted">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div>
            </div>

            <div class="col-md-6">
              <label for="cc-number" class="form-label">Credit card number</label>
              <input type="text" class="form-control" id="cc-number" placeholder="" required="">
              <div class="invalid-feedback">
                Credit card number is required
              </div>
            <img style="position: absolute; cursor: pointer; left: 855px; top: 1166.5px; z-index: 2147483644; width: 27px; height: 27px; border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 4px; transition: all 0.25s ease 0s;" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBmaWxsPSIjRkZGIiBkPSJNMCAwaDMydjMySDB6Ii8+PHBhdGggZD0iTTMyIDB2MzJIMFYwaDMyek0xNS42NDggOEg5LjZ2MTYuMDM4aDMuNDM2di01LjI3aDIuNjEyYzQuNjEzIDAgNi45MTktMS43OTQgNi45MTktNS4zODMgMC0zLjU5LTIuMzA2LTUuMzg0LTYuOTE5LTUuMzg0em0uMTYgMy4wMjVjMi4xNyAwIDMuMjU0Ljc4NiAzLjI1NCAyLjM2IDAgMS41NzMtMS4wODUgMi4zNi0zLjI1MyAyLjM2aC0yLjc3M3YtNC43MnoiIGZpbGw9IiMyMzIzMjAiLz48L2c+PC9zdmc+" class="_pwp-icon" alt="Checkout with Privacy" title="Checkout with Privacy"></div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">Expiration</label>
              <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
              <div class="invalid-feedback">
                Expiration date required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-cvv" class="form-label">CVV</label>
              <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
              <div class="invalid-feedback">
                Security code required
              </div>
            </div>
          </div>

          <hr class="my-4">
        <%= form_for [@goat, @booking] do |f| %>


              <%= f.hidden_field :start_date %>
              <%= hidden_field_tag :start_date, @start_date  %>
              <%= f.hidden_field :end_date %>
              <%= hidden_field_tag :end_date, @end_date  %>
              <%= f.submit "Confirm Your Booking", class: "w-100 btn btn-primary btn-lg"  %>
        <% end %>
      </div>
    </div>

app/views/goats/index.html.erb
<div class="containsAll container" style="padding-top: 27px">
<div class="position-filters dropdown">
  <button class="filter-category btn btn-secondary"  style="margin-bottom: 30px; margin-right: 10px;" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><i class="fa-solid fa-map-location-dot"></i></button>

  <button class="filter-category btn btn-secondary dropdown-toggle"  style="margin-bottom: 30px;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
   <%= image_tag "filter.png", class: "filter-image" %> Filters
  </button>

  <ul class="dropdown-menu">

      <% goat_categories.each do |category| %>
        <%= link_to category, goats_path(category: category), class: "dropdown-item" %>
      <% end %>
    </ul>
  </div>

  <div class="cards mb-10px">
    <% @goats.each do |goat| %>
      <div class="card animated_card">
        <%= link_to goat_path(goat.id, dates: params[:dates]), class: "position-relative" do %>
          <%= cl_image_tag(goat.photo.key, class: "card-img-top") %>
          <p class="star-icon m-0 px-2 mb-0">
            <i class="fa-solid fa-star star"></i> <%= goat.rating %>
          </p>
        <% end %>

        <div class="card-body">
          <div class="d-flex">
            <h5 class="card-title mb-0"><%= goat.name %></h5>
            <p class="price"><%= goat.price_per_day %>€/h</p>
          </div>
          <div class="d-flex justify-content-between">
            <span class="goat-category"><%= goat.category %></span>
            <%# <p class="card-text"><%= goat.description </p> %>
          </div>
          <% if current_user.favorited?(goat) %>
            <%= link_to unfavorite_goat_path(goat), data: { turbo_method: :patch } do %>
              <i class="fa-solid fa-heart heart-icon ml-10"></i>
            <% end %>
          <% else %>
            <%= link_to favorite_goat_path(goat), data: { turbo_method: :patch } do %>
              <i class="fa-regular fa-heart heart ml-10"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
</div>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Goat Map</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
      <div style="width: 100%; height: 100%;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
</div>

app/views/goats/show.html.erb
<%= link_to "<", goats_path, class: "returnbtn btn btn-primary" %>
<div class="p-4 p-md-5 mb-4 rounded flex" style="background-color: #798E77; color:white; border-radius: 10px!important">
  <div class="row g-5 justify-content-center">
    <div class="banner_show col-12 col-lg-8 px-4">
      <h1 class=" display-4 fst-italic"><%= @goat.name %></h1>
      <hr style="border: 2px solid; color: white;">
      <div class="d-flex justify-content-start align-items-center" style="height: 79%;">
        <p class="lead my-3"><%= @goat.description %></p>
      </div>
    </div>
    <div class="col-12 col-lg-4 order-first order-lg-last d-flex justify-content-center align-items-center">
      <div class="fill">
        <%= cl_image_tag(@goat.photo.key, height:333, width:368, crop:"fill") %>
      </div>
    </div>
  </div>
</div>
  <div class="row g-5">
    <div class="col-md-8">
      <div class="row">
        <div class="col-12">
          <div class="card rounded border w-100" style="border-radius: 10px!important;">
            <div class="card-body">
              <h5 class="card-title">Rating:
                <% @goat.rating.round(0).times do %>
                  <i class="fa-solid fa-star" style="font-size: 15px; color:#FFC978"></i>
                <% end %>
                <% (5 - @goat.rating.round(0)).times do %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
              </h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card rounded border w-100" style="border-radius: 10px!important;">
            <div class="card-body">
              <h5 class="card-title">Age:
                <strong><%= @goat.age %></strong>
              </h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-sm-6">
          <div class="card rounded border w-100 h-100" style="border-radius: 10px!important;">
            <div class="card-body text-center">
            <i class="fa-regular fa-face-grin-tongue-squint fs-2 text-primary mb-2"></i>
              <h5 class="card-title">Anti-Spit Training</h5>
              <p class="card-text" style="color: #7B7878; margin-top: 17px;">With supporting text below as a natural lead-in to additional content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card rounded border w-100  h-100" style="border-radius: 10px!important;">
            <div class="card-body text-center">
            <i class="fa-solid fa-car-burst fs-2 text-primary mb-2"></i>
              <h5 class="card-title">Comprehensive insurance coverage</h5>
              <p class="card-text" style="color: #7B7878; margin-top: 17px;">With supporting text below as a natural lead-in to additional content.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-sm-6">
          <div class="card rounded border w-100 h-100" style="border-radius: 10px!important;">
            <div class="card-body text-center">
            <i class="fa-solid fa-earth-europe fs-2 text-primary mb-2"></i>
              <h5 class="card-title">Bio-Green Certified</h5>
              <p class="card-text" style="color: #7B7878; margin-top: 17px;">With supporting text below as a natural lead-in to additional content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card rounded border w-100  h-100" style="border-radius: 10px!important;">
            <div class="card-body text-center">
            <i class="fa-solid fa-utensils fs-2 text-primary mb-2"></i>
              <h5 class="card-title">1 Acre/hour</h5>
              <p class="card-text" style="color: #7B7878; margin-top: 17px;">With supporting text below as a natural lead-in to additional content.</p>
            </div>
          </div>
        </div>
      </div>
      <article class="blog-post">
      <p><%= @goat.name %> is naturally curious. They are agile and well known for their ability to climb and balance in precarious places. This makes them the only ruminant to regularly climb trees. Due to their agility and inquisitiveness, they are notorious for escaping their pens by testing fences and enclosures, either intentionally or simply because they are used to climbing. If any of the fencing can be overcome, goats will almost inevitably escape. Goats have been found to be as intelligent as dogs by some studies.</p>
       </article>
      <hr />
      <div class="row my-4">
        <div class="col-12">
          <div class="card rounded border w-100">
            <div class="card-body">
              <h5 class="card-title">Location:
                <strong><%= @goat.address %></strong>
              </h5>
            </div>
          </div>
        </div>
      </div>
      <div style="width: 100%; height: 400px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="card mb-4 rounded-3 shadow w-100" style="border-radius: 10px!important;">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pricing</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">€<%= @goat.price_per_day %><small class="text-muted fw-light">/day</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>€<%= @goat.transport_fee %> <small class="text-muted fw-light">transport fee</small></li>
              <li>€<%= @goat.cleaning_fee %> <small class="text-muted fw-light">cleaning fee</small></li>
              <hr />
              <%total = @goat.price_per_day + @goat.cleaning_fee + @goat.cleaning_fee %>
              <li><strong>Total:</strong> €<%= total %></li>
            </ul>
            <%= link_to new_goat_booking_path(@goat, dates: params[:dates]), class: "w-100 btn btn-lg btn-outline-primary", style: "border-radius: 34px!important;" do %>
              Book <%= @goat.name %>
            <% end %>
          </div>
        </div>
      <div class="p-4 mb-3 rounded border position-relative" style="border-radius: 10px!important;">
      This is a rare find! <strong><%= @goat.name %> is usually booked!</strong>
        <span class="position-absolute top-0 start-50 translate-middle badge rounded-pill bg-danger hot-goat">
          HOT GOAT!
          <span class="visually-hidden">This goat is usually booked</span>
        </span>
      </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoatScape</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body style="margin-top: 94px";>
    <%= render "shared/navbar"%>

      <% if params[:controller] == "pages" && params[:action] == "home" %>
        <%= yield %>
      <% else %>
        <main class="container">
          <%= yield %>
        </main>
      <% end %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="banner d-flex justify-content-center align-items-center flex-column" style="height: 700px;">
    <div class="list d-flex justify-content-center align-items-center flex-column">
          <%= image_tag "logo.png", width: 600, class: "mb-4" %>
    <h2 class="bannerSubtitle">Oh My Goat!</h2>
      <%= link_to "/goats", class: "btn btn-primary btn-lg btn-seegoats" do %>
        See Goats
      <% end %>
    </div>
  </div>
</div>
<div class="list d-flex justify-content-center align-items-center pt-5 pb-5">
  <h2 mb-50>We rent goats for any occasion</h2>
</div>
<div class="list d-flex justify-content-center align-items-center pb-5">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1602631985686-1bb0e6a8696e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmlydGhkYXklMjBwYXJ0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60)">
    Birthdays
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1603988363607-e1e4a66962c6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fHlvZ2F8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60)">
    Yoga
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1533215740941-26df050d5278?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Z3Jhc3MlMjBnb2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60)">
    Lawn Care
  </div>
</div>

<div class="jumbotron jumbotron-fluid pb-5 mt-5">
    <div class="list d-flex justify-content-center align-items-center pt-5">
      <h2>See what our users have to say</h2>
      </div>
      <div class="container mb-10">
        <div class="list d-flex justify-content-center align-items-center mb-10">
          <div class="card-home p-3" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Kady Heron</h5>
                <p class="card-text"><i>"The goats were well-behaved and kind."</i></p>
          </div>
        </div>
  <div class="card-home p-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Janice Ian</h5>
      <p class="card-text"><i>"The best goat rental I've ever used!"</i></p>
    </div>
  </div>
  <div class="card-home p-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Gretchen Wieners</h5>
      <p class="card-text"><i>"I'll never practive goatless yoga again!"</i></p>
    </div>
  </div>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2022 Goatscape, Inc</p>
    <a href="/" class="col-md-2 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-6 justify-content-end">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link px-2 text-muted"%>
      </li>
      <li class="nav-item">
        <%= link_to "All goats", goats_path, class: "nav-link px-2 text-muted"%>
      </li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
  </footer>
</div>

app/views/shared/_search.html.erb
<% cat = [] %>
<% goat_categories.each do |category| %>
  <% cat << category %>
<% end %>

<%= form_with url: "/goats", method: :get do |form| %>
  <%= form.label :address, "Location:" %>
  <%= form.text_field :address %>
  <%= form.label :category, "Category:" %>
  <%= form.select :category, cat %>
  <input placeholder="Select Dates" name="dates" data-flatpickr-target="calendarInput" data-controller="flatpickr" style="border: none; width: 220px;"><i class="fa-regular fa-calendar" style="color: #5d6e5b; font-size: 15px;"></i>
  <%= form.submit "Search" %>
<% end %>